### ISSUE TITLE
AutoIt replacement functions

### ISSUE THREAD

**Issue by kmorgan2** [kmorgan2/ResTool-NXT#32]
We need functions in Python (preferably not using a 3rd-party library) that replace AutoIt functions like WinWait, WinActivate, Send, ControlClick, etc. Basically any function used in the master branch to control programs needs to be ported somehow to the python branch.

**Comment by tmalauskas** [comment]
Seeing as though importing the pywinauto library is out of the picture, I think our best bet is to manually grab the functions we need from [https://github.com/pywinauto/pywinauto/tree/master/pywinauto](url). Thoughts?

**Comment by kmorgan2** [comment]
pywinauto is very heavy as a library. It has a lot of backend dependency that we would need to model. Probably a better option would be to model the dll calls from the AutoIt source. these can be replaced by ctypes.windll.<dll>.<function>  calls in most cases.

**Comment by kmorgan2** [comment]
Source of Autoit available here: https://github.com/ellysh/au3src/tree/master/src.
Most info will be in script_win.cpp

**Comment by kmorgan2** [comment]
PyWinAuto will work fine after all.
